#!/usr/bin/env bash
# Configures Nginx to use a custom 404 page with the string "Ceci n'est pas une page"

green_echo() {
    echo -e "\e[32m$1\e[0m"
}

#------------------------
# Update and Install Nginx
#------------------------
green_echo "Updating and installing Nginx."
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

green_echo "Nginx installed."

#------------
# Start Nginx
#------------
green_echo "Starting Nginx."
sudo service nginx start

#-----------------
# Allow Nginx HTTP
#-----------------
green_echo "Allowing Nginx HTTP."
sudo ufw allow 'Nginx HTTP'

#------------------------
# Granting User Ownership
#------------------------
green_echo "Granting user ownership."
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
green_echo "Done."

#---------------------
# Backup Default Index
#---------------------
green_echo "Backing up default index."
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

#-----------------
# Create New Index
#-----------------
green_echo "Creating new index."
echo "Hello World!" | sudo tee /var/www/html/index.html

#--------------------
# Configure Redirection
#--------------------
green_echo "Configuring redirection."
sudo sed -i '/location \/ {/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

#----------------------
# Create Custom 404 Page
#----------------------
green_echo "Creating custom 404 page."
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

#-------------------------
# Configure Custom 404 Page
#-------------------------
green_echo "Configuring custom 404 page."
sudo sed -i '/^}/i \ \n\t# Custom 404 error page\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\tinternal;\n\t\troot /var/www/html;\n\t}\n' /etc/nginx/sites-available/default

#--------------
# Restart Nginx
#--------------
green_echo "Restarting Nginx."
sudo service nginx restart

green_echo "Configuration completed. ✅"