#!/usr/bin/env bash
# This script is diplaying "Best School" 10 times

names='Best School'
counter=1

while [ $counter -le 10 ]
do
   echo "$names"

   # Check id the counter is at 9, if so, print "hi"
   if [ $counter -eq 9 ]; then
    echo "hi"
   fi

   ((counter++))
done