#!/usr/bin/env bash
# This script is diplaying "Best School" 10 times

names='Best School'
counter=0

while [ $counter -lt 10 ]
do
   # Check id the counter is at 9, if so, print "hi"
   if [ $counter -eq 3 ]; then
    echo "bad luck"
   elif [ $counter -eq 7 ]; then
    echo "good luck"
   else
    echo "Best School"
   fi

   ((counter++))
done